### ISSUE TITLE
Add all the tests

### ISSUE THREAD

**Issue by calavera** [docker/engine-api#1]
we're piggybacking on docker for testing. We should add our own tests.

We can investigate if we can use the mock in Sam Alba's client to make them work:

https://github.com/samalba/dockerclient/tree/master/mockclient

**Comment by calavera** [comment]
We also have to keep in mind that once all the backend interfaces are here, we'll have very nice starting point:

https://github.com/docker/docker/blob/master/api/server/router/container/backend.go
https://github.com/docker/docker/blob/master/api/server/router/volume/backend.go
https://github.com/docker/docker/blob/master/api/server/router/network/backend.go
...

**Comment by dnephin** [comment]
I think you could auto-generate the mock using https://github.com/vektra/mockery and `go generate`. That way it stays current with any API changes.

I'm thinking of doing something like that for the client.

**Comment by calavera** [comment]
that sounds very interesting indeed.

**Comment by MHBauer** [comment]
Given the importance of this it would be good to make sure to have conforming tests in isolation from any external users, as well as conforming tests by external users. If `mockery` gets us some internal tests, that would be good.

**Comment by calavera** [comment]
I've started to add basic tests with mocks. See:

https://github.com/docker/engine-api/pull/66
https://github.com/calavera/engine-api/commit/ba33f314f02150a93ff9c09d54bb88b6e6765a71

Please, go nuts and add more tests.

**Comment by calavera** [comment]
Just an update:

we don't have "all the tests" yet, but we have a lot of them already thanks to @vdemeester:

https://github.com/docker/engine-api/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+%22Add+unit+test%22

I'm not sure at which point we want to consider this solved, but I'm already pretty happy about it.
