### ISSUE TITLE
FTBFS with go-units 0.2.0

### ISSUE THREAD

**Issue by onlyjob** [docker/engine-api#130]
Engine-api v0.2.2 and v0.2.3 FTBFS when built with latest release of [go-units](https://github.com/docker/go-units/releases) v0.2.0:

~~~~
src/github.com/docker/engine-api/types/container/host_config.go:185: undefined: units.Ulimit 
~~~~

**Comment by calavera** [comment]
You can use https://github.com/docker/go-units/tree/v0.3.0.

**Comment by onlyjob** [comment]
Thanks. :)
