### ISSUE TITLE
An error occurred trying to connect: context deadline exceeded

### ISSUE THREAD

**Issue by blacktop** [docker/engine-api#149]
So what seems to be happening is I have an app and when I try and run:
```go
defaultHeaders := map[string]string{"User-Agent": "engine-api-cli-1.0"}
client, err = docker.NewClient("unix:///var/run/docker.sock", "v1.22", nil, defaultHeaders)
if err != nil {
	log.Fatal(err)
}

ctx, cancel := context.WithTimeout(context.Background(), 120*time.Second)
defer cancel()

// Check if client can connect
_, err = client.Info(ctx)
if err != nil {
	handleClientError(err)
}
```
I get the error: `An error occurred trying to connect: context deadline exceeded` **IF** I am running it from a go installed bin.

So if I do a `go run main.go` from the `go get` source directory `GOPATH/src/github.com/me/mythang` it works just fine, but when I then do a `go install` and then `cd ~` and run the install go bin I get the above error.  Very strange indeed?

Any help much preesh.

**Comment by calavera** [comment]
Sorry, but this is not an issue with the library. I recommend you to check your go enviroment and possible the program your using that snippet in:

![info-bug](https://cloud.githubusercontent.com/assets/1050/13861222/5b303572-ec49-11e5-8b13-78760d912e01.gif)

**Comment by blacktop** [comment]
@calavera haha that is an awesome way to handle issues!!! :+1: 

Thank you I will debug my app further.
