### ISSUE TITLE
Backward compatibility for container filters

### ISSUE THREAD

**Issue by nishanttotla** [docker/engine-api#171]
Reference: https://github.com/docker/engine-api/blob/master/types/filters/parse.go
Currently, the `Args` struct looks like this
```
type Args struct {
	fields map[string]map[string]bool
}
```
but not too long ago, it looked like this
```
type Args map[string][]string
```
So basically I can’t use the newer client to work with older daemons, because I will get a json unmarshaling error. This is a problem for Swarm since we're moving to the `engine-api` and can't support older daemons on the cluster as a result.

Current Swarm PR blocked due to this issue: https://github.com/docker/swarm/pull/1983

This issue is in the same category as #144.

**Comment by nishanttotla** [comment]
Ping @calavera @thaJeztah creating issue here so that discussion is saved :)

**Comment by thaJeztah** [comment]
Thanks @nishanttotla!

**Comment by calavera** [comment]
I guess we could try to version that `ToParam` function in the filters. I think the change was introduced in `1.21`. We could do something like:

```go
func ToParamWithVersion(arg Args, version string) (string, error) {
  if version < "1.21" {
     // serialize old version
  } else {
    return ToParam(args)
  }
}
```

**Comment by nishanttotla** [comment]
@calavera thanks! I was just working on a fix that does the exact same thing. I'll open a PR later today.

**Comment by nishanttotla** [comment]
One issue though, is that it's unclear where the daemon version will come from. Since `filters` is a separate package inside of `types`, and the version is stored inside the `client` package, the only way I can see to do this is to pass the version to `ToParam` from all places making the call. WDYT @calavera?
