### ISSUE TITLE
missing license

### ISSUE THREAD

**Issue by onlyjob** [docker/engine-api#172]
Files in [client/transport/cancellable](../tree/master/client/transport/cancellable) refer to missing "BSD-style" `LICENSE` file.

**Comment by onlyjob** [comment]
Over three weeks passed. Could someone please clarify the license?

**Comment by MHBauer** [comment]
Do we need to throw a copy of https://github.com/golang/net/blob/master/LICENSE into that folder? I believe it is a partial fork of https://github.com/golang/net/blob/master/context/ctxhttp/ctxhttp.go .

**Comment by calavera** [comment]
> Do we need to throw a copy of https://github.com/golang/net/blob/master/LICENSE into that folder?

Do that :tada:

**Comment by onlyjob** [comment]
Yes, `LICENSE` file with full text of the license should be in this folder. Thanks, @MHBauer.

**Comment by vdemeester** [comment]
#208 merged, let's close that one.

**Comment by onlyjob** [comment]
Thanks!
