### ISSUE TITLE
Engine-api built with Go(<=1.4) won't work with Docker daemon built with Go(>=1.6)

### ISSUE THREAD

**Issue by Random-Liu** [docker/engine-api#189]
When using engine-api built with Go(<=1.4) with Docker daemon built with Go(>=1.6), it keeps complaining `"Error response from daemon: 400 Bad Request: malformed Host header"`.

I think the reason is that:

1. After https://github.com/golang/go/commit/6e11f45ebdbc7b0ee1367c80ea0a0c0ec52d6db5, the http server in Go 1.6 will validate the [HTTP Host header](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23) conforming to HTTP 1.1 (See https://github.com/golang/go/issues/13624)
2. On the http client side, Go writes the HTTP Host header with `request.Host` or `request.URL.Host`(if the former is empty) (See [here](https://github.com/golang/go/blob/a6557a05a03490af3b26f97f9a4ce99c7c773fe5/src/net/http/request.go#L404-L410))
3. When using the [default docker endpoint](https://github.com/docker/engine-api/blob/68a7b6bebf8f57d559b7788a46c55045438747b9/client/client_unix.go#L6) (`unix:///var/run/docker.sock`), engine-api will set `request.Host=""`, `request.URL.Host="/var/run/docker.sock"` (See [set request.URL.Host](https://github.com/docker/engine-api/blob/68a7b6bebf8f57d559b7788a46c55045438747b9/client/request.go#L85-L87) and [set request.Host](https://github.com/docker/engine-api/blob/68a7b6bebf8f57d559b7788a46c55045438747b9/client/request.go#L131))
4. When the engine-api is built with Go >= 1.5, everything goes well, because Go will [clean up the Host](https://github.com/golang/go/blob/master/src/net/http/request.go#L523) making both `request.Host` and `request.URL.Host` to "". Then the HTTP Host header will be "". (See https://github.com/golang/go/issues/11206))
5. But when the engine-api is built with Go<=1.4, Go [won't clean up the Host](https://github.com/golang/go/blob/release-branch.go1.4/src/net/http/request.go#L368-L373), so the HTTP Host header will be `"/var/run/docker.sock"`. It will break Go 1.6 http server side validation in 1. because `'/'`is not a valid character, causing `400 Bad Request: malformed Host header`.

I could fix this by set some random but valid thing like "docker.sock" in the `request.URL.Host`. If it is not used for unix endpoint, why don't we just set it to a valid Host?

Hope this could be fixed, thanks! :)

More information https://github.com/kubernetes/kubernetes/issues/23809

**Comment by duglin** [comment]
See https://github.com/docker/docker/issues/20865

**Comment by Random-Liu** [comment]
@duglin Yeah, I saw that one. :)

I think in docker/docker#20865, people were mainly talking about the **Docker CLI**. While this one is a little different:
1) People may use engine-api to build anything, they may need to use Go 1.4 because of some reason.
2) It's easy to update engine-api.

**Comment by vdemeester** [comment]
I do agree with @Random-Liu, maybe we should *handle* this in here too.
/cc @calavera @MHBauer

**Comment by Random-Liu** [comment]
Thanks, @vdemeester!

BTW, we are switching from go-dockerclient to the official engine-api, :). There is no such problem in go-dockerclient (See [here](https://github.com/fsouza/go-dockerclient/blob/c47e4f4e477828cb3e226acfff18b9e6c044ebdb/client.go#L400))

**Comment by MHBauer** [comment]
We have control of the default client, so we should be able to handle it. Is there a way uses of `engine-api` can work around this by providing a customized client? We should work out both ways, if possible.

**Comment by duglin** [comment]
Explicitly setting the value to something meaningful and valid should be easy enough to do.  A PR would be welcome....

**Comment by Random-Liu** [comment]
@duglin Thanks, I'll send a PR soon :)

**Comment by calavera** [comment]
Fixed by #190.
