### ISSUE TITLE
Exposing all ports

### ISSUE THREAD

**Issue by ZedCode** [docker/engine-api#206]
Hi,

I see that in the type for Config there is a field for ExposedPorts, however, I'm trying to replicate the functionality of `docker run -dP [image name]`.

I have tried just creating an empty map (not that I expected this to work):
```
emptyMap := make(map[nat.Port]struct{})
configOptions := container.Config{Image: c.RegistryURL + "/" + containerType, ExposedPorts: emptyMap}
hostConfig := container.HostConfig{}
networkConfig := network.NetworkingConfig{}
createResponse, err := cli.ContainerCreate(context.Background(), &configOptions, &hostConfig, &networkConfig, containerName)
```
However, the end result of this is just a container with no exposed ports. Am I missing the correct way to expose all ports like the -P flag does?

**Comment by vdemeester** [comment]
Hi @ZedCode, you have to use the attribute `PublishAllPorts` of HostConfig. Something like that :

```go
emptyMap := make(map[nat.Port]struct{})
configOptions := container.Config{Image: c.RegistryURL + "/" + containerType, ExposedPorts: emptyMap}
hostConfig := container.HostConfig{ PublishAllPorts: true }
networkConfig := network.NetworkingConfig{}
createResponse, err := cli.ContainerCreate(context.Background(), &configOptions, &hostConfig, &networkConfig, containerName)
```

**Comment by ZedCode** [comment]
Ah, perfect! I was looking in the wrong types file :)
