### ISSUE TITLE
Network need expose an interface NetworkInspectWithRaw

### ISSUE THREAD

**Issue by HackToday** [docker/engine-api#207]
Right now, the docker issue https://github.com/docker/docker/issues/22231
because of engine-api 
```
NetworkInspect(ctx context.Context, networkID string) (types.NetworkResource, error)
```
it need a new interface like container/image inspect, defined as following
```
NetworkInspectWithRaw(ctx context.Context, networkID string) (types.NetworkResource, []byte, error)
```
Then the inspect can -f (go template) with `Id` like container/image did

**Comment by HackToday** [comment]
#dibs

**Comment by HackToday** [comment]
ping @calavera and @vdemeester  WDYT.

**Comment by vdemeester** [comment]
@HackToday Sorry for the delay.. Wanted to answer before but got.. carried away.
Looking at the docker/docker issue, I think it makes sense to be consistent (having those methods for Containers, Images, Network and Volumes).

So I would definitely be ok with it. I also think, we might want to make sure all these 4 (container, image, network and volume) have both methods.

**Comment by calavera** [comment]
yep, that's the way to go. You can read about the issue with Go templates further in this issue:

https://github.com/docker/go/pull/3

**Comment by thaJeztah** [comment]
wow, that's one massive PR; sad it didn't get any attention

**Comment by thaJeztah** [comment]
@HackToday did you want to work on this issue?

**Comment by HackToday** [comment]
sure @thaJeztah  will check it , Miss that those days :0

**Comment by HackToday** [comment]
@thaJeztah  One question for that, as this depend on engine-api, should I send a PR for engine-api, after that merged, then I send PR to docker-engine ? 
Do we need some vendor to do that ?

**Comment by thaJeztah** [comment]
@HackToday I think in this case, it's good to open a PR here first, and open a PR to docker/docker after its merged here. Can you do PRs for all types? (Networks, Volumes etc) https://github.com/docker/engine-api/issues/207#issuecomment-215022955
