### ISSUE TITLE
Return http client and scheme?

### ISSUE THREAD

**Issue by nishanttotla** [docker/engine-api#212]
Currently, the `engine-api` client does not export or allow a way to get the underlying http client and scheme.

Would it be possible to add a function to do this?

**Comment by vdemeester** [comment]
Hi @nishanttotla , what would be the use case ? (/me curious :angel:)

**Comment by nishanttotla** [comment]
@vdemeester in Swarm, we have this function
```
func closeIdleConnections(client *http.Client) {
	if tr, ok := client.Transport.(*http.Transport); ok {
		tr.CloseIdleConnections()
	}
}
```
that needs the http client. At a couple of other places, we also pass requests to the agent Engines directly. Perhaps @vieux or @dongluochen know better about the reasoning behind that.

**Comment by dongluochen** [comment]
There are several use cases to set HTTP client parameters: 
1. Users want to set MaxIdleConnsPerHost and DisableKeepAlives to control the number of TCP connections for a cluster. The manager becomes a bottleneck in a large cluster. 
2. TCP dead peer detection. If a receiver disappears abruptly, it'd take very long (15 min on Linux default settings) to detect connection failure. TCP user timeout can reduce this detection time. See https://github.com/samalba/dockerclient/pull/202.

**Comment by calavera** [comment]
You can initialize a client outside and pass it to the API:

https://github.com/docker/engine-api/blob/master/client/client.go#L69

You can do whatever you want with it without having to expose it again from within the API.

**Comment by nishanttotla** [comment]
@calavera that's pretty much what we currently do - create the client using [samalba/dockerclient](https://github.com/samalba/dockerclient), then pass it on to `engine-api`, and were hoping to only use the latter.

**Comment by nishanttotla** [comment]
Closing this issue, because we're fixing it in Swarm: https://github.com/docker/swarm/pull/2206
