### ISSUE TITLE
Unable to mock client in unit tests

### ISSUE THREAD

**Issue by aanm** [docker/engine-api#24]
Hey, I was trying to mock the docker client behavior by overwriting the httpclient. Unfortunately the httpclient is private https://github.com/docker/engine-api/blob/master/client/client.go#L29
Anyway to workaround this?
Thanks!

**Comment by vdemeester** [comment]
@aanm I started simple, using `httptest`, something like this : https://github.com/vdemeester/engine-api/commit/472901c622a9d72c6d4f43dbce65e9fa29611c20.

At some point we will need more advanced stuff but I think, by doing these tests simple and increment on them each time we need will be good :stuck_out_tongue:.

**Comment by dnephin** [comment]
There should be some way to mock it out. Maybe we could add an alternative "constructor" that accepts an `*http.Client` ?

**Comment by vdemeester** [comment]
I'm not sure if it's overkill to add something just for tests or mock by overwritting the httpclient. The `httptest` package is made for that and I feel it's not gonna be hard to handle all the API calls.

**Comment by dnephin** [comment]
It's not necessarily just for testing. Users of the library may want to configure the client differently. For example, right now there is no way to set the timeout yourself, you're forced to use the hardcoded 32 seconds. That was fine for a CLI, but it's not really acceptable for a library.

My other concern is that using a real http server is not a true unit test. It wastes a lot of time hitting unrelated code. A unit test should be as fast as possible, which would be to use a mock.

It even says so in the [`httptest` docs](https://golang.org/pkg/net/http/httptest/#Server)! "A Server ... for use in end-to-end HTTP tests." end-to-end tests, not unit test!

**Comment by vdemeester** [comment]
@dnephin true :stuck_out_tongue:

**Comment by calavera** [comment]
we're still in time to break the api. I'd rather minimize the number of constructors and just change the `NewClient` one now that we can still do it.

**Comment by aanm** [comment]
should the `httpClient` client attribute be public then?

**Comment by calavera** [comment]
private, pretty please :pray:

just change the `NewClient` constructor to be:

```go
func NewClient(address, version string, httpClient *http.Client, headers...)
```

**Comment by aanm** [comment]
> ```go
func NewClient(address, version string, httpClient *http.Client, headers...)
```

I like this

**Comment by dnephin** [comment]
I like it too

**Comment by calavera** [comment]
I've added an initial test in https://github.com/docker/engine-api/pull/54, so it can be used as reference.

**Comment by aanm** [comment]
@calavera But how can I mock the endpoint requests? I'm trying to mock with an `http.Transport` structure that has this method `func (t *mockTransport) RoundTrip(req *http.Request) (*http.Response, error) {` but it doesn't seems to be working out.

Can you help me out?

**Comment by wrfly** [comment]
ping @aanm https://github.com/moby/moby/pull/34383
