### ISSUE TITLE
Add event management

### ISSUE THREAD

**Issue by bfirsh** [docker/engine-api#246]
[The main thing missing from this library that is stopping people from switching from samalba/dockerclient is event management.](https://github.com/samalba/dockerclient/issues/238)

@vdemeester has created [a separate library](https://github.com/vdemeester/docker-events) for parsing and handling events. Something like this should probably be in this library.

**Comment by vdemeester** [comment]
@bfirsh I can make a PR porting those piece of code in `engine-api`.
@docker/core-engine-api-maintainers wdyt ?

**Comment by calavera** [comment]
> has created a separate library for parsing and handling events. Something like this should probably be in this library.

Why does it need to be in this repository? Can't those people use @vdemeester repo directly? FWIW, it looks pretty nice.

**Comment by bfirsh** [comment]
I guess depends on what the intent of this library is. If it is intended to be a library for building apps on the Remote API, handling of events seems a pretty essential part of that because they are part of the API.

To put it another way – if events are near impossible to use without another library, that library should probably be part of engine-api.

**Comment by vdemeester** [comment]
This is now part of the api `github.com/docker/docker/client/...`
