### ISSUE TITLE
Pointer to time.Duration

### ISSUE THREAD

**Issue by bogh** [docker/engine-api#337]
Hi

I've been using the API and I did not understand why `Client.ContainerStop` accepts a pointer to `time.Duration` for the `timeout` parameter?

https://github.com/docker/engine-api/blob/master/client/container_stop.go#L13

Is this intended and has a meaning? I found it difficult the need to pass this as an address.

**Comment by Asarew** [comment]
Just for future reference (even though this repo is deprecated?): A beginning golang colleague asked me the same question and find this issue after some Google'ing. [The answer is quite simple](https://github.com/docker/cli/blob/38c1895021337cf78e2c84bd4e633e724040c5be/opts/duration.go#L28-L29)

**Comment by thaJeztah** [comment]
Yes, @Asarew's answer is correct; let me close this one, but feel free to continue the conversation
