### ISSUE TITLE
ContainerExecAttach wrong request body?

### ISSUE THREAD

**Issue by vikstrous** [docker/engine-api#381]
If I'm reading this correctly, it looks like ContainerExecAttach posts to `/exec/(id)/start` but takes in the wrong type for the body (types.ExecConfig instead of types.ExecStartCheck. See https://docs.docker.com/engine/reference/api/docker_remote_api_v1.25/#exec-start for the documentation of that api. It seems to me that the only parameter actually relevant here is TTY because you always want `{Detach: false}`. Similarly, the only parameter to ContainerExecStart should also be TTY because you always want `{Detach: true}`.

**Comment by paralin** [comment]
+1, definitely the wrong request body.

**Comment by thaJeztah** [comment]
Opened a pull-request here: https://github.com/moby/moby/pull/35128
