### ISSUE TITLE
ContainerStart with memory limit

### ISSUE THREAD

**Issue by chinuy** [docker/engine-api#391]
In cmd, I can `docker run -it --rm -m 128m [image]` to limit the memory usage.
However, I image that would an option in `types.ContainerStartOptions`, but it it not.

Is there another option I can use. Or this configuration is not implemented yet?

**Comment by vdemeester** [comment]
Hi @chinuy, thanks for the report, but this project is frozen (and we should make sure it is in github but that's another story).

Related to your question, the way to limit memory using the API is to pass a specific `HostConfig` when creating the container (https://github.com/moby/moby/blob/master/client/container_create.go#L22) and set `HostConfig.Resource.Memory` (see https://github.com/moby/moby/blob/master/api/types/container/host_config.go#L311) 😉

**Comment by chinuy** [comment]
thank you for the kindly replying. This solve my problem.:)
