### ISSUE TITLE
Obtaining image ID after a build

### ISSUE THREAD

**Issue by cyphar** [docker/engine-api#49]
Currently, there's no real way (other than tagging or parsing server output manually) to get what the final image ID of a successful build is. This is quite annoying, and it should be possible to have a field in `types.ImageBuildResponse` -- we'd just need to append to the end of the build output a JSON object describing the final ImageID. Or we'll have to implement build IDs.

**Comment by duglin** [comment]
Not near my computer to verify which flag but we recently added a -s flag, I think, which will return just the build/image id

-Doug

**Comment by duglin** [comment]
I take that back , I forgot that we "fixed" `-q` instead of added `-s`.  Using `-q` will JUST return the image ID upon success, nothing to parse.

**Comment by cyphar** [comment]
@duglin Cheers. I didn't know that.
